/**
 * Single source of truth for the RO -> EN route pairs.
 * Consumed by src/lib/routeMap.ts (client language switcher) and by
 * scripts/generate-sitemap.mjs (hreflang alternates in the sitemap).
 */
export const RO_TO_EN = {
  "/": "/en",
  "/despre-mine": "/en/about",
  "/blog": "/en/blog",
  "/contact": "/en/contact",
  "/termeni-si-conditii": "/en/terms-and-conditions",
  "/gdpr": "/en/gdpr",
  "/politica-cookies": "/en/cookie-policy",
  "/servicii": "/en/services",
  "/harta-site": "/en/sitemap",
  "/calculator-despagubiri": "/en/compensation-calculator",
  "/servicii/urmarire-penala": "/en/services/criminal-investigation",
  "/servicii/masuri-preventive": "/en/services/preventive-measures",
  "/servicii/infractiuni-contra-persoanei": "/en/services/offenses-against-persons",
  "/servicii/criminalitate-economica": "/en/services/financial-crime",
  "/servicii/infractiuni-de-coruptie-si-fapte-legate-de-exercitarea-functiei-publice":
    "/en/services/corruption-and-public-office-offenses",
  "/servicii/investigatii-privind-activele-cripto": "/en/services/crypto-asset-investigations",
  "/servicii/cauze-penale-privind-droguri": "/en/services/drug-offenses",
  "/servicii/spalare-de-bani-si-ascundere-de-bunuri": "/en/services/money-laundering-and-asset-concealment",
  "/servicii/neglijenta-profesionala-si-malpraxis": "/en/services/professional-negligence-and-malpractice",
  "/servicii/infractiuni-rutiere-cu-victime": "/en/services/road-traffic-offenses",
  "/servicii/raspundere-penala-incidente-locul-de-munca": "/en/services/workplace-criminal-liability",
  "/servicii/reprezentarea-victimelor-in-procese-penale": "/en/services/victim-representation-in-criminal-cases",
  "/servicii/audiere-politie-parchet": "/en/services/police-prosecutor-questioning",
  "/servicii/perchezitie-domiciliara": "/en/services/home-search",
  "/servicii/perchezitie-informatica": "/en/services/computer-search",
  "/servicii/avocat-diicot": "/en/services/diicot-lawyer",
  "/servicii/avocat-dna": "/en/services/dna-lawyer",
  "/servicii/evaziune-fiscala": "/en/services/tax-evasion",
  "/servicii/inselaciune-frauda": "/en/services/fraud-and-deception",
  "/servicii/delapidare": "/en/services/embezzlement",
  "/servicii/fals-si-uz-de-fals": "/en/services/forgery-and-use-of-forgery",
  "/servicii/bancruta-frauduloasa": "/en/services/fraudulent-bankruptcy",
  "/servicii/frauda-informatica": "/en/services/computer-fraud",
  "/servicii/dare-luare-de-mita": "/en/services/bribery-giving-and-taking",
  "/servicii/trafic-de-influenta": "/en/services/influence-peddling",
  "/servicii/abuz-in-serviciu": "/en/services/abuse-of-office",
  "/servicii/neglijenta-in-serviciu": "/en/services/negligence-in-office",
  "/servicii/conflict-de-interese": "/en/services/conflict-of-interest",
  "/servicii/fonduri-europene": "/en/services/eu-funds-fraud",
  "/servicii/retinere-24-ore": "/en/services/police-custody-24-hours",
  "/servicii/arest-preventiv": "/en/services/pre-trial-detention",
  "/servicii/control-judiciar": "/en/services/judicial-control",
  "/servicii/arest-la-domiciliu": "/en/services/house-arrest",
};
