/**
 * Single source of truth for the indexable routes.
 * Used by scripts/prerender.mjs (static HTML) and scripts/generate-sitemap.mjs.
 */
export const SITE_ORIGIN = "https://avocatpenalbucuresti.ro";

export const ROUTES = [
  "/",
  "/despre-mine",
  "/blog",
  "/calculator-despagubiri",
  "/contact",
  "/servicii",
  "/servicii/urmarire-penala",
  "/servicii/masuri-preventive",
  "/servicii/infractiuni-contra-persoanei",
  "/servicii/criminalitate-economica",
  "/servicii/infractiuni-de-coruptie-si-fapte-legate-de-exercitarea-functiei-publice",
  "/servicii/investigatii-privind-activele-cripto",
  "/servicii/cauze-penale-privind-droguri",
  "/servicii/detinere-droguri-consum-propriu",
  "/servicii/grup-infractional-organizat",
  "/servicii/trafic-international-de-droguri",
  "/servicii/spalare-de-bani-si-ascundere-de-bunuri",
  "/servicii/sechestru-asigurator",
  "/servicii/confiscare",

  "/servicii/neglijenta-profesionala-si-malpraxis",
  "/servicii/infractiuni-rutiere-cu-victime",
  "/servicii/raspundere-penala-incidente-locul-de-munca",
  "/servicii/reprezentarea-victimelor-in-procese-penale",
  "/servicii/despagubiri-accident-rutier",
  "/servicii/despagubiri-vatamare-corporala",
  "/servicii/loviri-vatamare-corporala",
  "/servicii/violenta-domestica",
  "/servicii/lipsire-de-libertate-amenintare",
  "/servicii/santaj-hartuire",
  "/servicii/viol-agresiune-sexuala",
  "/servicii/omor-ucidere-din-culpa",
  "/servicii/audiere-politie-parchet",
  "/servicii/perchezitie-domiciliara",
  "/servicii/perchezitie-informatica",
  "/servicii/avocat-diicot",
  "/servicii/avocat-dna",
  "/servicii/evaziune-fiscala",
  "/servicii/inselaciune-frauda",
  "/servicii/delapidare",
  "/servicii/fals-si-uz-de-fals",
  "/servicii/bancruta-frauduloasa",
  "/servicii/frauda-informatica",
  "/servicii/dare-luare-de-mita",
  "/servicii/trafic-de-influenta",
  "/servicii/abuz-in-serviciu",
  "/servicii/neglijenta-in-serviciu",
  "/servicii/conflict-de-interese",
  "/servicii/fonduri-europene",
  "/en/services/asset-freezing-order",
  "/en/services/confiscation",
  "/servicii/alcool-la-volan",
  "/en/services/drunk-driving",
  "/servicii/droguri-la-volan",
  "/en/services/drug-driving",
  "/servicii/parasirea-locului-accidentului",
  "/en/services/leaving-the-accident-scene",
  "/servicii/refuz-prelevare-probe-biologice",
  "/en/services/refusal-to-provide-biological-samples",
  "/servicii/conducere-fara-permis",
  "/en/services/driving-without-a-licence",
  "/servicii/accident-rutier-cu-victime",
  "/en/services/road-accident-with-victims",
  "/servicii/retinere-24-ore",
  "/servicii/arest-preventiv",
  "/servicii/control-judiciar",
  "/servicii/arest-la-domiciliu",
  "/harta-site",
  "/termeni-si-conditii",
  "/gdpr",
  "/politica-cookies",
  "/en",
  "/en/about",
  "/en/blog",
  "/en/contact",
  "/en/terms-and-conditions",
  "/en/gdpr",
  "/en/cookie-policy",
  "/en/sitemap",
  "/en/compensation-calculator",
  "/en/services",
  "/en/services/criminal-investigation",
  "/en/services/preventive-measures",
  "/en/services/offenses-against-persons",
  "/en/services/financial-crime",
  "/en/services/corruption-and-public-office-offenses",
  "/en/services/crypto-asset-investigations",
  "/en/services/drug-offenses",
  "/en/services/drug-possession-personal-use",
  "/en/services/organized-crime-group",
  "/en/services/international-drug-trafficking",
  "/en/services/money-laundering-and-asset-concealment",

  "/en/services/professional-negligence-and-malpractice",
  "/en/services/road-traffic-offenses",
  "/en/services/workplace-criminal-liability",
  "/en/services/victim-representation-in-criminal-cases",
  "/en/services/road-accident-compensation",
  "/en/services/bodily-injury-compensation",
  "/en/services/assault-and-bodily-injury",
  "/en/services/domestic-violence",
  "/en/services/unlawful-detention-and-threats",
  "/en/services/blackmail-and-harassment",
  "/en/services/rape-and-sexual-assault",
  "/en/services/homicide-and-manslaughter",
  "/en/services/police-prosecutor-questioning",
  "/en/services/home-search",
  "/en/services/computer-search",
  "/en/services/diicot-lawyer",
  "/en/services/dna-lawyer",
  "/en/services/tax-evasion",
  "/en/services/fraud-and-deception",
  "/en/services/embezzlement",
  "/en/services/forgery-and-use-of-forgery",
  "/en/services/fraudulent-bankruptcy",
  "/en/services/computer-fraud",
  "/en/services/bribery-giving-and-taking",
  "/en/services/influence-peddling",
  "/en/services/abuse-of-office",
  "/en/services/negligence-in-office",
  "/en/services/conflict-of-interest",
  "/en/services/eu-funds-fraud",
  "/en/services/police-custody-24-hours",
  "/en/services/pre-trial-detention",
  "/en/services/judicial-control",
  "/en/services/house-arrest",
];

/** Sub-service (cluster) pages: lower sitemap priority than their pillar page. */
export const SUB_SERVICE_ROUTES = new Set([
  "/servicii/loviri-vatamare-corporala",
  "/en/services/assault-and-bodily-injury",
  "/servicii/violenta-domestica",
  "/en/services/domestic-violence",
  "/servicii/lipsire-de-libertate-amenintare",
  "/en/services/unlawful-detention-and-threats",
  "/servicii/santaj-hartuire",
  "/en/services/blackmail-and-harassment",
  "/servicii/viol-agresiune-sexuala",
  "/en/services/rape-and-sexual-assault",
  "/servicii/omor-ucidere-din-culpa",
  "/en/services/homicide-and-manslaughter",
  "/servicii/audiere-politie-parchet",
  "/servicii/perchezitie-domiciliara",
  "/servicii/perchezitie-informatica",
  "/servicii/avocat-diicot",
  "/servicii/avocat-dna",
  "/servicii/detinere-droguri-consum-propriu",
  "/servicii/grup-infractional-organizat",
  "/servicii/trafic-international-de-droguri",
  "/en/services/police-prosecutor-questioning",
  "/en/services/home-search",
  "/en/services/computer-search",
  "/en/services/diicot-lawyer",
  "/en/services/dna-lawyer",
  "/en/services/drug-possession-personal-use",
  "/en/services/organized-crime-group",
  "/en/services/international-drug-trafficking",
  "/servicii/retinere-24-ore",

  "/servicii/arest-preventiv",
  "/servicii/control-judiciar",
  "/servicii/arest-la-domiciliu",
  "/en/services/police-custody-24-hours",
  "/en/services/pre-trial-detention",
  "/en/services/judicial-control",
  "/en/services/house-arrest",
]);

/** Priority hints for the sitemap. */
export function priorityFor(route) {
  if (route === "/" || route === "/en") return "1.0";
  if (SUB_SERVICE_ROUTES.has(route)) return "0.8";
  if (route.startsWith("/servicii/") || route.startsWith("/en/services/")) return "0.9";
  if (["/despre-mine", "/contact", "/en/about", "/en/contact"].includes(route)) return "0.8";
  if (["/termeni-si-conditii", "/gdpr", "/politica-cookies", "/en/terms-and-conditions", "/en/gdpr", "/en/cookie-policy", "/harta-site", "/en/sitemap"].includes(route))
    return "0.3";
  return "0.6";
}
